global:
  alex-gfy:
    spine_ASN: 65000
    lo0: 10.255.255.0/24
    spine_peers: &id001
    - 172.16.80.1
    - 172.16.81.1
    MTU: 9214
alex-gfy-spine1:
  interfaces:
    loopback0:
      ipv4: 10.255.255.0
      mask: 32
    Ethernet1:
      ipv4: 172.16.80.0
      mask: 31
    Ethernet2:
      ipv4: 172.16.80.2
      mask: 31
    Ethernet3:
      ipv4: 172.16.80.4
      mask: 31
    Ethernet4:
      ipv4: 172.16.80.6
      mask: 31
  BGP:
    ASN: 65000
alex-gfy-spine2:
  interfaces:
    loopback0:
      ipv4: 10.255.255.255
      mask: 32
    Ethernet1:
      ipv4: 172.16.81.0
      mask: 31
    Ethernet2:
      ipv4: 172.16.81.2
      mask: 31
    Ethernet3:
      ipv4: 172.16.81.4
      mask: 31
    Ethernet4:
      ipv4: 172.16.81.6
      mask: 31
  BGP:
    ASN: 65000
alex-gfy-Brdr1:
  interfaces:
    loopback0:
      ipv4: 10.255.255.1
      mask: 32
  BGP:
    ASN: 65001
alex-gfy-Brdr2:
  interfaces:
    loopback0:
      ipv4: 10.255.255.2
      mask: 32
  BGP:
    ASN: 65001
alex-gfy-leaf1:
  interfaces:
    loopback0:
      ipv4: 10.255.255.1
      mask: 32
    loopback1:
      ipv4: 10.255.254.1
      mask: 32
  BGP:
    ASN: 65002
    spine-peers: *id001
    spine-ASN: 65000
  MLAG: Odd
alex-gfy-leaf2:
  interfaces:
    loopback0:
      ipv4: 10.255.255.2
      mask: 32
    loopback1:
      ipv4: 10.255.254.1
      mask: 32
  BGP:
    ASN: 65003
    spine-peers: *id001
    spine-ASN: 65000
  MLAG: Even
alex-gfy-leaf3:
  interfaces:
    loopback0:
      ipv4: 10.255.255.3
      mask: 32
    loopback1:
      ipv4: 10.255.254.2
      mask: 32
  BGP:
    ASN: 65004
    spine-peers: *id001
    spine-ASN: 65000
  MLAG: Odd
alex-gfy-leaf4:
  interfaces:
    loopback0:
      ipv4: 10.255.255.4
      mask: 32
    loopback1:
      ipv4: 10.255.254.2
      mask: 32
  BGP:
    ASN: 65005
    spine-peers: *id001
    spine-ASN: 65000
  MLAG: Even
