global:
  tz2:
    spine_ASN: 65000
    lo0: 10.255.255.0/24
    spine_peers: &id001
    - 10.255.255.0
    - 10.255.255.254
    - 10.255.255.255
    MTU: 9214
tz2-spine1:
  interfaces:
    loopback0:
      ipv4: 10.255.255.0
      mask: 32
    Ethernet1:
      ipv4: 172.16.80.0
      mask: 31
    Ethernet2:
      ipv4: 172.16.80.2
      mask: 31
    Ethernet3:
      ipv4: 172.16.80.4
      mask: 31
    Ethernet4:
      ipv4: 172.16.80.6
      mask: 31
    Ethernet63:
      ipv4: 172.16.80.8
      mask: 31
    Ethernet62:
      ipv4: 172.16.80.10
      mask: 31
  BGP:
    ASN: 65000
tz2-spine2:
  interfaces:
    loopback0:
      ipv4: 10.255.255.254
      mask: 32
    Ethernet1:
      ipv4: 172.16.81.0
      mask: 31
    Ethernet2:
      ipv4: 172.16.81.2
      mask: 31
    Ethernet3:
      ipv4: 172.16.81.4
      mask: 31
    Ethernet4:
      ipv4: 172.16.81.6
      mask: 31
    Ethernet63:
      ipv4: 172.16.81.8
      mask: 31
    Ethernet62:
      ipv4: 172.16.81.10
      mask: 31
  BGP:
    ASN: 65000
tz2-spine3:
  interfaces:
    loopback0:
      ipv4: 10.255.255.255
      mask: 32
    Ethernet1:
      ipv4: 192.16.82.0
      mask: 31
    Ethernet2:
      ipv4: 192.16.82.2
      mask: 31
    Ethernet3:
      ipv4: 192.16.82.4
      mask: 31
    Ethernet4:
      ipv4: 192.16.82.6
      mask: 31
    Ethernet63:
      ipv4: 192.16.82.8
      mask: 31
    Ethernet62:
      ipv4: 192.16.82.10
      mask: 31
  BGP:
    ASN: 65000
tz2-leaf1:
  interfaces:
    loopback0:
      ipv4: 10.255.255.1
      mask: 32
    loopback1:
      ipv4: 10.255.254.1
      mask: 32
    Ethernet2:
      ipv4: 192.16.82.0
      mask: 31
    Ethernet3:
      ipv4: 192.16.82.0
      mask: 31
  BGP:
    ASN: 65001
    spine-peers: *id001
    spine-ASN: 65000
  MLAG: Odd
tz2-leaf2:
  interfaces:
    loopback0:
      ipv4: 10.255.255.2
      mask: 32
    loopback1:
      ipv4: 10.255.254.1
      mask: 32
    Ethernet2:
      ipv4: 192.16.82.2
      mask: 31
    Ethernet3:
      ipv4: 192.16.82.2
      mask: 31
  BGP:
    ASN: 65001
    spine-peers: *id001
    spine-ASN: 65000
  MLAG: Even
tz2-leaf3:
  interfaces:
    loopback0:
      ipv4: 10.255.255.3
      mask: 32
    loopback1:
      ipv4: 10.255.254.2
      mask: 32
    Ethernet2:
      ipv4: 192.16.82.4
      mask: 31
    Ethernet3:
      ipv4: 192.16.82.4
      mask: 31
  BGP:
    ASN: 65002
    spine-peers: *id001
    spine-ASN: 65000
  MLAG: Odd
tz2-leaf4:
  interfaces:
    loopback0:
      ipv4: 10.255.255.4
      mask: 32
    loopback1:
      ipv4: 10.255.254.2
      mask: 32
    Ethernet2:
      ipv4: 192.16.82.6
      mask: 31
    Ethernet3:
      ipv4: 192.16.82.6
      mask: 31
  BGP:
    ASN: 65002
    spine-peers: *id001
    spine-ASN: 65000
  MLAG: Even
tz2-Brdr1:
  interfaces:
    loopback0:
      ipv4: 10.255.255.5
      mask: 32
    loopback1:
      ipv4: 10.255.254.3
      mask: 32
    Ethernet2:
      ipv4: 192.16.82.8
      mask: 31
    Ethernet3:
      ipv4: 192.16.82.8
      mask: 31
  BGP:
    ASN: 65003
    spine-peers: *id001
    spine-ASN: 65000
  MLAG: Odd
tz2-Brdr2:
  interfaces:
    loopback0:
      ipv4: 10.255.255.6
      mask: 32
    loopback1:
      ipv4: 10.255.254.3
      mask: 32
    Ethernet2:
      ipv4: 192.16.82.10
      mask: 31
    Ethernet3:
      ipv4: 192.16.82.10
      mask: 31
  BGP:
    ASN: 65003
    spine-peers: *id001
    spine-ASN: 65000
  MLAG: Even
