global:
  spine_ASN: 65000
  lo0: 10.255.255.0/24
  MTU: 9214
tz7-spine1:
  interfaces:
    loopback0:
      ipv4: 10.255.255.0
      mask: 32
    Ethernet1:
      ipv4: 10.255.255.1
      mask: 31
    Ethernet2:
      ipv4: 10.255.255.3
      mask: 31
    Ethernet3:
      ipv4: 10.255.255.5
      mask: 31
    Ethernet4:
      ipv4: 10.255.255.7
      mask: 31
    Ethernet5:
      ipv4: 10.255.255.9
      mask: 31
    Ethernet6:
      ipv4: 10.255.255.11
      mask: 31
    Ethernet61:
      ipv4: 10.255.255.13
      mask: 31
    Ethernet62:
      ipv4: 10.255.255.15
      mask: 31
  BGP:
    ASN: 65000
tz7-spine2:
  interfaces:
    loopback0:
      ipv4: 10.255.255.255
      mask: 32
    Ethernet1:
      ipv4: 10.255.255.2
      mask: 31
    Ethernet2:
      ipv4: 10.255.255.4
      mask: 31
    Ethernet3:
      ipv4: 10.255.255.6
      mask: 31
    Ethernet4:
      ipv4: 10.255.255.8
      mask: 31
    Ethernet5:
      ipv4: 10.255.255.10
      mask: 31
    Ethernet6:
      ipv4: 10.255.255.12
      mask: 31
    Ethernet61:
      ipv4: 10.255.255.13
      mask: 31
    Ethernet62:
      ipv4: 10.255.255.15
      mask: 31
  BGP:
    ASN: 65000
tz7-leaf1:
  interfaces:
    loopback0: {}
    Ethernet1:
      ipv4: 10.255.255.1
      mask: 31
    Ethernet2:
      ipv4: 10.255.255.2
      mask: 31
  BGP:
    ASN: 65002
  MLAG: Odd
tz7-leaf2:
  interfaces:
    loopback0: {}
    Ethernet1:
      ipv4: 10.255.255.3
      mask: 31
    Ethernet2:
      ipv4: 10.255.255.4
      mask: 31
  BGP:
    ASN: 65003
  MLAG: Even
tz7-leaf3:
  interfaces:
    loopback0: {}
    Ethernet1:
      ipv4: 10.255.255.5
      mask: 31
    Ethernet2:
      ipv4: 10.255.255.6
      mask: 31
  BGP:
    ASN: 65004
  MLAG: Odd
tz7-leaf4:
  interfaces:
    loopback0: {}
    Ethernet1:
      ipv4: 10.255.255.7
      mask: 31
    Ethernet2:
      ipv4: 10.255.255.8
      mask: 31
  BGP:
    ASN: 65005
  MLAG: Even
tz7-leaf5:
  interfaces:
    loopback0: {}
    Ethernet1:
      ipv4: 10.255.255.9
      mask: 31
    Ethernet2:
      ipv4: 10.255.255.10
      mask: 31
  BGP:
    ASN: 65006
  MLAG: Odd
tz7-leaf6:
  interfaces:
    loopback0: {}
    Ethernet1:
      ipv4: 10.255.255.11
      mask: 31
    Ethernet2:
      ipv4: 10.255.255.12
      mask: 31
  BGP:
    ASN: 65007
  MLAG: Even
tz7-borderleaf1:
  interfaces:
    loopback0:
      ipv4: 10.255.255.253
      mask: 32
    Ethernet1:
      ipv4: 10.255.255.13
      mask: 31
    Ethernet2:
      ipv4: 10.255.255.14
      mask: 31
  BGP:
    ASN: 65001
  MLAG: Odd
tz7-borderleaf2:
  interfaces:
    loopback0:
      ipv4: 10.255.255.254
      mask: 32
    Ethernet1:
      ipv4: 10.255.255.15
      mask: 31
    Ethernet2:
      ipv4: 10.255.255.16
      mask: 31
  BGP:
    ASN: 65001
  MLAG: Even
